### ISSUE TITLE
Light/Switch Entities - No longer working in 2026.3

### ISSUE THREAD

**Issue by jessica12ryan** [uvjustin/alarmdotcom#524]
Please provide as much detail as possible. It's helpful to include Home Assistant debug logs from this integration. Instructions for enabling debugging are available at https://github.com/pyalarmdotcom/alarmdotcom/wiki/How-to-Test-&-Debug#enable-code-debugging. (Alarmdotcom debug logs are verbose, so don't forget to disable debug logging when you're done!)

**Describe the bug**
After upgrading to Home Assistant Core 2026.3.0, the light and switch entities are no longer available.

**To Reproduce**

1. Update to Home Assistant 2026.3.0
2. Go to alarm.com entities
3. Any light or switch entities will appear as unavailable and no longer in use by the integration

**Expected behavior**
Light and switch entities should be able to be turned on/off and not appear as unavailable

**Screenshots**

**Home Assistant Version:**
2026.3.0

**Additional context**
```
Log details (ERROR)
Logger: homeassistant.components.light
Source: helpers/entity_platform.py:455
integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 10:43:51 AM (2 occurrences)
Last logged: 2:00:28 PM

Error while setting up alarmdotcom platform for light: module 'homeassistant.components.light' has no attribute 'COLOR_MODE_ONOFF'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/alarmdotcom/light.py", line 33, in async_setup_entry
    async_add_entities(
    ~~~~~~~~~~~~~~~~~~^
        Light(
        ^^^^^^
    ...<3 lines>...
        for device in controller.api.devices.lights.values()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 574, in _async_schedule_add_entities_for_entry
    new_entities if type(new_entities) is list else list(new_entities)
                                                    ~~~~^^^^^^^^^^^^^^
  File "/config/custom_components/alarmdotcom/light.py", line 34, in <genexpr>
    Light(
    ~~~~~^
        controller=controller,
        ^^^^^^^^^^^^^^^^^^^^^^
        device=device,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/alarmdotcom/light.py", line 57, in __init__
    [light.COLOR_MODE_BRIGHTNESS] if self._device.brightness else [light.COLOR_MODE_ONOFF]
                                                                   ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.components.light' has no attribute 'COLOR_MODE_ONOFF'. Did you mean: 'COLOR_MODES_COLOR'?
```

```
Logger: pyalarmdotcomajax.websockets.client
Source: /usr/local/lib/python3.14/site-packages/pyalarmdotcomajax/websockets/client.py:150
First occurred: 10:44:36 AM (24 occurrences)
Last logged: 2:04:22 PM

Unexpected WebSocket error
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/site-packages/pyalarmdotcomajax/websockets/client.py", line 137, in _connect
    await self._async_handle_message(json.loads(msg.data))
  File "/usr/local/lib/python3.14/site-packages/pyalarmdotcomajax/websockets/client.py", line 175, in _async_handle_message
    message = process_raw_message(raw_message, self._device_registry)
  File "/usr/local/lib/python3.14/site-packages/pyalarmdotcomajax/websockets/messages.py", line 44, in process_raw_message
    return EventMessage(message, device)
                                 ^^^^^^
UnboundLocalError: cannot access local variable 'device' where it is not associated with a value
```

**Comment by ibasebcast** [comment]
I've noticed that several parts of this integration appear to be falling behind recent Home Assistant changes, which is likely contributing to the issues people are seeing with entities becoming unavailable.

To help move things forward, I’ve created a fork of this repository and have begun reviewing and updating the codebase to bring it back in line with current Home Assistant requirements. My goal is to resolve the existing issues, improve stability, and add additional functionality over time.

Because I work directly with Alarm.com systems through a security integration business and have partner-level access to their platform, I’m also able to test functionality in ways that many users cannot. This should allow me to validate fixes more thoroughly and potentially expose additional device capabilities.

If anyone is interested in following the progress, testing updates, or contributing, the fork is available here:

https://github.com/ibasebcast/ha-alarmdotcom

I’ll be pushing updates as fixes and improvements are completed.

**Comment by trentonamor** [comment]
@ibasebcast  you should sync with @rmatte and @nulledy (see issue #513 )

**Comment by Valdorama** [comment]
@ibasebcast THanks for doing that - do we know if your fork is the consensus version moving forward?

**Comment by ibasebcast** [comment]
I plan on maintaining and improving my fork.
